version: '3'

services:
  database:
    image: mysql:latest
    ports:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: contactdb

  app:
    build: .
    ports:
      - 8080:8080
    links:
      - database
